# Enforce the 'restricted' Pod Security Standard on the namespace.
apiVersion: v1
kind: Namespace
metadata:
  name: streamingapp
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
