apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    # IRSA: bind this SA to an IAM role (least-privilege AWS access for pods, no static keys)
    eks.amazonaws.com/role-arn: arn:aws:iam::852373397151:role/streamingapp-pod-role
